# Generated by Django 5.0 on 2024-01-18 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_notification_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
