# Generated by Django 5.0 on 2024-01-22 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_rename_is_deleted_email_is_deleted_by_recipient_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
