# Generated by Django 5.0 on 2024-01-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0006_delete_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
    ]
