# Generated by Django 5.0 on 2024-01-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0007_email_is_starred'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='is_draft',
        ),
        migrations.RemoveField(
            model_name='email',
            name='is_starred',
        ),
        migrations.AddField(
            model_name='email',
            name='is_starred_by_recipient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='is_starred_by_sender',
            field=models.BooleanField(default=False),
        ),
    ]
