# Generated by Django 5.0 on 2024-01-24 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0008_remove_email_is_draft_remove_email_is_starred_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='is_starred_by_recipient',
            new_name='is_starred',
        ),
        migrations.RemoveField(
            model_name='email',
            name='is_starred_by_sender',
        ),
    ]
