# Generated by Django 5.0 on 2024-01-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0010_remove_email_is_starred_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='recipient',
            field=models.EmailField(max_length=255),
        ),
    ]
