# Generated by Django 5.0 on 2024-01-18 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_snippet_notification_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='snippet',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='sender',
            new_name='sender_name',
        ),
    ]
