# Generated by Django 5.0 on 2024-01-22 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_rename_is_deleted_email_is_deleted_by_recipient_and_more'),
        ('notifications', '0005_rename_snippet_notification_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mail.email'),
        ),
    ]
