# Generated by Django 5.0 on 2024-01-22 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_notification_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='email',
            new_name='related_email',
        ),
    ]
